name: HelloWorld
description: This is your personal project
version: v0.7.0
author: scott+demo2@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: scott+demo2@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-12-14 19:37:59'
    modifiedAt: '2022-12-14 19:37:59'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: scott+demo2@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-12-14 19:37:59'
    modifiedAt: '2022-12-14 19:37:59'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_totals
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: scott+demo2@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-12-14 19:37:59'
    modifiedAt: '2022-12-14 19:37:59'
    datasets:
      inputs:
      - datasets/farmers-markets
      - datasets/irs-zipcode-data
      outputs:
      - datasets/farmers_market_tax_report
    dependencies: {}
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: scott+demo2@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2023-03-16 20:21:14'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customers_orders
    dependencies: {}
  pipelines/cleanup_data:
    name: cleanup_data
    description: ''
    author: scott+demo2@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 19:56:29'
    modifiedAt: '2023-03-09 19:57:23'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/customers:
    name: customers
    description: All the customers
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/report:
    name: report
    description: Final report for the bank
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: scott+demo2@prophecy.io
    createdAt: '2022-12-14 19:37:58'
    modifiedAt: '2022-12-14 19:37:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1342
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2022-12-14 19:37:58'
        modifiedAt: '2022-12-14 19:37:58'
  datasets/scottdemo_customers_orders:
    name: scottdemo_customers_orders
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-02-14 19:02:49'
    modifiedAt: '2023-02-14 19:02:49'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-02-14 19:02:49'
        modifiedAt: '2023-02-14 19:02:49'
templates: {}
jobs:
  jobs/HelloProd-customers:
    name: HelloProd-customers
    description: ''
    fabricUID: 1572
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 12 * * ? *
    timeout: null
    alerting:
      emails: scott@prophecy.io
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/customers_orders
    - pipelines/report_top_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-02-10 03:28:19'
    modifiedAt: '2023-02-10 03:28:19'
    author: scott+demo2@prophecy.io
  jobs/HelloDev-customers:
    name: HelloDev-customers
    description: ''
    fabricUID: 1571
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: scott@prophecy.io
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/customers_orders
    - pipelines/report_top_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-02-10 03:24:54'
    modifiedAt: '2023-02-10 03:24:54'
    author: scott+demo2@prophecy.io
libraries: []
subgraphs:
  subgraphs/CleanupSubgraph:
    name: CleanupSubgraph
    description: ''
    author: scott+demo2@prophecy.io
    language: python
    mode: batch
    createdAt: '2023-03-09 19:57:23'
    modifiedAt: '2023-03-09 19:57:23'
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
