name: HelloWorld
description: This is your personal project
version: v4.0
author: scott+demo2@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: scott_demo2_team
  buildSystem: wheel
  author: null
  createdAt: '2023-03-27 15:13:13'
pipelines:
  pipelines/silver_customers_orders:
    name: silver_customers_orders
    description: Processes and transforms order and customer data from bronze to silver
      tables. It joins orders with customer details, filters invalid zip codes, and
      calculates income brackets by zip code. The pipeline also identifies high-income
      areas and assigns sequence IDs to customers.
    author: scott+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-13 16:49:10'
    datasets:
      inputs:
      - datasets/bronze_customers
      - datasets/bronze_irs_zipcode
      - datasets/bronze_orders
      outputs:
      - datasets/silver_customers
      - datasets/silver_order_customer_details
      - datasets/silver_orders
    subgraphs:
    - subgraphs/bronze_customer_zip
    dependencies: {}
  pipelines/gold_sales:
    name: gold_sales
    description: ''
    author: scott+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-13 18:32:25'
    datasets:
      inputs:
      - datasets/silver_order_customer_details
      outputs:
      - datasets/gold_sales_by_zip_date
      - datasets/gold_total_sales_by_customer
    subgraphs: []
    dependencies: {}
  pipelines/gold_top_customers:
    name: gold_top_customers
    description: ''
    author: scott+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-13 18:45:24'
    datasets:
      inputs:
      - datasets/gold_total_sales_by_customer
      outputs:
      - datasets/gold_top50_customers_by_spend
    subgraphs: []
    dependencies: {}
  pipelines/silver_zip_codes:
    name: silver_zip_codes
    description: ''
    author: scott+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-13 18:54:01'
    datasets:
      inputs:
      - datasets/bronze_irs_zipcode
      outputs:
      - datasets/silver_irs_zipcode
    subgraphs: []
    dependencies: {}
  pipelines/raw_bronze:
    name: raw_bronze
    description: The pipeline consists of several modules that read in and manipulate
      data related to customers, orders, and IRS tax data. The raw_customers module
      reads in customer data from a CSV file and creates a Spark DataFrame with a
      specified schema. The bronze_orders module writes the input DataFrame to a Delta
      Lake table for efficient querying and analysis of payment data. The ReformatCustomers
      module reformats customer data for improved quality and consistency. The raw_orders
      module reads in raw order data and creates a DataFrame with a specified schema.
      The ReformatIRS module reformats IRS tax data for easier analysis and reporting.
      The ReformatOrders module reformats order data for improved consistency and
      accuracy. The bronze_irs_zipcode module saves the input DataFrame as a Delta
      table for data warehousing and analysis. The bronze_customers module writes
      the input DataFrame to a Delta table for further data processing and analysis.
      The raw_irs_zipcode module reads in IRS tax data by zip code and aggregates
      it into a Spark DataFrame for further analysis and insights.
    author: scott+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-07-13 19:20:19'
    datasets:
      inputs:
      - datasets/raw_customers
      - datasets/raw_irs_zipcode
      - datasets/raw_orders
      outputs:
      - datasets/bronze_customers
      - datasets/bronze_irs_zipcode
      - datasets/bronze_orders
    subgraphs: []
    dependencies: {}
  pipelines/raw_bronze_subgraph:
    name: raw_bronze_subgraph
    description: ''
    author: vlaunir@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-23 13:29:12'
    datasets:
      inputs:
      - datasets/raw_dynamic_source
      outputs:
      - datasets/raw_dynamic_table
    subgraphs: []
    dependencies: {}
  pipelines/customer_orders:
    name: gold_customer_orders
    description: Combines customer details with order information to create a unified
      dataset. The pipeline joins the `bronze_orders` and `bronze_customers` dataframes
      based on the `customer_id` column. It then selects specific columns from the
      joined dataframe and renames them accordingly. Additionally, it calculates the
      age of the account based on the `account_open_date`, converts the `full_name`
      column to uppercase, and assigns an `amount_flag` based on the value of the
      `AMOUNT` column.
    author: vlaunir@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-23 15:17:51'
    datasets:
      inputs:
      - datasets/bronze_customers
      - datasets/bronze_orders
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/bronze_orders:
    name: bronze_orders
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-12 21:07:12'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-12 21:07:12'
  datasets/bronze_customers:
    name: bronze_customers
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-12 21:08:08'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-12 21:08:08'
  datasets/bronze_irs_zipcode:
    name: bronze_irs_zipcode
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-12 21:09:09'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-12 21:09:09'
  datasets/silver_irs_zipcode:
    name: silver_irs_zipcode
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 16:59:23'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 16:59:23'
  datasets/silver_orders:
    name: silver_orders
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 17:02:28'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 17:02:28'
  datasets/silver_customers:
    name: silver_customers
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 17:13:56'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 17:13:56'
  datasets/gold_total_sales_by_customer:
    name: gold_total_sales_by_customer
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 17:43:15'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 17:43:15'
  datasets/silver_order_customer_details:
    name: silver_order_customer_details
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 18:23:03'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 18:23:03'
  datasets/gold_sales_by_zip_date:
    name: gold_sales_by_zip_date
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 18:38:51'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 18:38:51'
  datasets/gold_top50_customers_by_spend:
    name: gold_top50_customers_by_spend
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 19:05:05'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: Database
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 19:05:05'
  datasets/raw_customers:
    name: raw_customers
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 19:22:07'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 19:22:07'
  datasets/raw_orders:
    name: raw_orders
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 19:22:43'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 19:22:43'
  datasets/raw_irs_zipcode:
    name: raw_irs_zipcode
    description: ''
    author: scott+demo2@prophecy.io
    createdAt: '2023-07-13 19:23:27'
    mode: batch
    physicalDatasets:
      HelloDev:
        fabricId: 1571
        datasetType: File
        description: ''
        author: scott+demo2@prophecy.io
        createdAt: '2023-07-13 19:23:27'
  datasets/raw_dynamic_table:
    name: bronze_dynamic_table
    description: ''
    author: vlaunir@prophecy.io
    createdAt: '2024-07-23 14:10:21'
    mode: batch
    physicalDatasets:
      Dev:
        fabricId: 9664
        datasetType: Database
        description: ''
        author: vlaunir@prophecy.io
        createdAt: '2024-07-23 14:10:21'
  datasets/raw_dynamic_source:
    name: raw_dynamic_source
    description: ''
    author: vlaunir@prophecy.io
    createdAt: '2024-07-23 16:50:29'
    mode: batch
    physicalDatasets:
      Dev:
        fabricId: 9664
        datasetType: File
        description: ''
        author: vlaunir@prophecy.io
        createdAt: '2024-07-23 16:50:29'
templates: {}
jobs:
  jobs/DBX_Workflow_Vlaunir_HelloWorld:
    name: DBX_Workflow_Vlaunir_HelloWorld
    description: ''
    fabricUID: 9664
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: Small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/gold_sales
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2024-07-25 19:39:44'
    author: vlaunir@prophecy.io
    models: []
  jobs/test:
    name: test
    description: ''
    fabricUID: 9664
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: Small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-08-02 18:39:32'
    author: vlaunir@prophecy.io
    models: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/MyLimit:
      name: MyLimit
      category: Transform
      subCategory: ''
      description: null
      author: scott+demo2@prophecy.io
      mode: batch
      files:
      - scott_demo2_team_helloworld/gems/MyLimit.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2023-11-08 18:07:56'
  dependencies: null
functions:
  author: null
  createdAt: '2023-03-27 15:13:13'
  udfs:
    udfs/rand_zip_index:
      name: rand_zip_index
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: scott+demo2@prophecy.io
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs:
  subgraphs/bronze_customer_zip:
    name: bronze_customer_zip
    description: ''
    author: vlaunir@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2024-07-30 15:01:42'
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-07-23T15:17:53.522852Z'
  name: plibMaven
  version: 8.0.29
  id: '307010185'
  createdAt: '2024-07-23T15:17:53.522779Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-08-01T18:27:40.116Z'
  name: ProphecyLibsPython
  version: 1.9.9
  id: '1002289140'
  createdAt: '2024-07-23T15:17:53.522922Z'
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
- type: pypi
  modifiedAt: '2024-07-23T14:22:24.344Z'
  package: s3fs
  name: s3fs
  description: ''
  enabled: true
  id: AY_8YZHatANSlli-JkVWB
  createdAt: '2024-07-23T14:22:24.344Z'
  entity: Project
  editable: true
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-23 13:36:17'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-23 13:36:21'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
